name: chemistry_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^11.3.1
  youtube_player_flutter: ^9.1.1
  shared_preferences: ^2.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.0.11
  android_intent_plus: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.8
  url_launcher: ^6.3.1
  fl_chart: ^0.63.0
  flutter_local_notifications: ^17.1.2
  package_info_plus: ^8.3.0
  provider: ^6.1.1





  # ✅ Dialogflow package
  http: ^1.2.1
  googleapis_auth: ^1.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/dialogflow_service_account.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app.png"
